[package]
name = 'cv-convert'
description = 'Type conversions among famous Rust computer vision libraries'
version = '0.26.0'
authors = ['jerry73204', 'phial3']
edition = '2021'
documentation = 'https://github.com/phial3/cv-convert'
repository = 'https://github.com/phial3/cv-convert'
homepage = 'https://github.com/phial3/cv-convert'
readme = 'README.md'
license = 'MIT'

[features]
default = [
    "image",
    "ndarray",
    "nalgebra",
    "imageproc",
]
image = ["dep:image"]
ndarray = ["dep:ndarray", "dep:yuvutils-rs"]
nalgebra = ["dep:nalgebra"]
imageproc = ["dep:imageproc"]
# sys
tch = ["dep:tch"]
rsmpeg = ["dep:rsmpeg"]
opencv = ["dep:opencv"]
full = ["tch", "rsmpeg", "opencv"]
# test
test-tch = ["tch/download-libtorch"]

[dev-dependencies]
rand = '0.10'
approx = '0.5'
itertools = '0.15'
rgb = "0.8"
pix = "1.0"
coolor = "1.0"
imgref = "1.11"
palette = "0.7"
fast_image_resize = "6.1"

[dependencies]
half = '2.6'
anyhow = '1.0'
strum = "0.28"
strum_macros = "0.28"
num-traits = '0.2'
image = { version = '0.25', default-features = true, optional = true }
nalgebra = { version = '0.35', default-features = true, optional = true }
ndarray = { version = '0.17', default-features = true, optional = true }
yuvutils-rs = { version = '0.8', optional = true }
imageproc = { version = '0.27', default-features = true, optional = true }
tch = { version = '0.24', default-features = true, optional = true}
opencv = { version = '0.100', default-features = true, optional = true, features = ["clang-runtime"] }
rsmpeg = { git = "https://gitee.com/phial3/rsmpeg", branch = "dev", optional = true, features = [
    "ffmpeg8_1", "link_system_ffmpeg"
] }
