[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-shlib-undefined", "-C", "link-arg=-fno-lto"]

[env]
PYO3_USE_ABI3_FORWARD_COMPATIBILITY="true"
LIBTORCH="/opt/homebrew/Cellar/pytorch/2.5.1_3/"